# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs Dev debug build"

  lane :build do
      gradle(task: "clean")
      gradle(task: "assembleDebug")
#      gradle(task: "app:test")

        sh "bash ./screenshott_new.sh"
  end


end
